bot_name: "fkk-2015-10"
bot_type: "fkk"
log_level: "INFO"
timezone: "America/New_York"
entry_time: "13:14:00"
entry_time_observation_period: 300
delta: -0.35
width: 10
sma_period: 5
intraday_move_pct: 0.3
max_position: 1
test_mode: false
force_open_position: false